# Generated by Django 5.0.7 on 2025-07-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("instructions", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProteinRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "req_type",
                    models.CharField(
                        choices=[("EAR", "EAR"), ("RNI", "RNI"), ("AMDR", "AMDR")],
                        max_length=4,
                    ),
                ),
                ("age_min", models.PositiveSmallIntegerField(help_text="起始年龄，单位: 岁")),
                ("age_max", models.PositiveSmallIntegerField(help_text="终止年龄，单位: 岁")),
                (
                    "value",
                    models.CharField(
                        help_text="定量或区间数值，如 '60' 或 '8-20'", max_length=20
                    ),
                ),
                ("unit", models.CharField(help_text="单位，如 g/d 或 %E", max_length=10)),
            ],
            options={
                "ordering": ["sex", "req_type", "age_min"],
                "unique_together": {("sex", "req_type", "age_min")},
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(blank=True, max_length=30)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.recipe",
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "ingredient")},
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recommender.RecipeIngredient", to="recommender.ingredient"
            ),
        ),
    ]
