# Generated by Django 5.0.7 on 2025-07-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")], max_length=1
                    ),
                ),
                (
                    "pal_level",
                    models.CharField(
                        choices=[("I", "PAL I"), ("II", "PAL II"), ("III", "PAL III")],
                        max_length=4,
                    ),
                ),
                ("age_min", models.PositiveSmallIntegerField()),
                ("age_max", models.PositiveSmallIntegerField()),
                ("value", models.CharField(max_length=20)),
                ("unit", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["sex", "pal_level", "age_min"],
                "unique_together": {("sex", "pal_level", "age_min")},
            },
        ),
    ]
