# Generated by Django 5.0.7 on 2025-07-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0002_energyrequirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("image_path", models.CharField(blank=True, max_length=200)),
                ("calories", models.CharField(blank=True, max_length=50)),
                ("nutrition", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("cook_time", models.CharField(blank=True, max_length=50)),
                ("difficulty", models.CharField(blank=True, max_length=20)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("servings", models.CharField(blank=True, max_length=20)),
                ("steps", models.JSONField(blank=True, null=True)),
                ("rating_sum", models.PositiveIntegerField(default=4)),
                ("rating_count", models.PositiveIntegerField(default=1)),
                (
                    "recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="recommender.recipe",
                    ),
                ),
            ],
        ),
    ]
