# Generated by Django 5.2.4 on 2025-07-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_recipe_recipeingredient_recipenutrition_recipestep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetip',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='match_rate',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating_count',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=30, help_text='烹饪时间（分钟）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default=5, help_text='烹饪步骤，每步用换行符分隔'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='is_main',
            field=models.BooleanField(default=False, help_text='是否为主要食材'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default='2-3人份', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='fruit.RecipeIngredient', to='fruit.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fruit.ingredient'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.DeleteModel(
            name='RecipeNutrition',
        ),
        migrations.DeleteModel(
            name='RecipeStep',
        ),
        migrations.DeleteModel(
            name='RecipeTip',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='product_id',
        ),
    ]
