# Generated by Django 5.0.7 on 2025-07-14 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fruit", "0004_favoriteingredient_fridgeitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCookedRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("calories", models.CharField(blank=True, max_length=50)),
                ("protein", models.CharField(blank=True, max_length=50)),
                ("fat", models.CharField(blank=True, max_length=50)),
                ("carbohydrates", models.CharField(blank=True, max_length=50)),
                ("fiber", models.CharField(blank=True, max_length=50)),
                ("sodium", models.CharField(blank=True, max_length=50)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fruit.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooked_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
