# Generated by Django 5.2.4 on 2025-07-16 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0005_usercookedrecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalorieRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('breakfast_food', models.CharField(blank=True, max_length=200)),
                ('breakfast_calories', models.IntegerField(default=0)),
                ('lunch_food', models.CharField(blank=True, max_length=200)),
                ('lunch_calories', models.IntegerField(default=0)),
                ('dinner_food', models.CharField(blank=True, max_length=200)),
                ('dinner_calories', models.IntegerField(default=0)),
                ('daily_target', models.IntegerField(default=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='UserCookedRecipe',
        ),
    ]
