# Generated by Django 5.2.4 on 2025-07-16 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0006_usercalorierecord_delete_usercookedrecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='身高（厘米）', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='体重（公斤）', max_digits=5, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True)),
                ('activity_level', models.CharField(choices=[('I', '低活动度（久坐少动）'), ('II', '中活动度（日常活动）'), ('III', '高活动度（经常运动）')], default='II', max_length=5)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
